CREATE TABLE IF NOT EXISTS bookmarks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT DEFAULT 'No description',
    rating INTEGER CHECK (rating >= 0) CHECK (5 >= rating)
);